---
services:
  waffles:
    container_name: waffles
    image: toozej/waffles:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    labels:
      - "traefik.enable=false"
      # labels below for publishing as web service
      # - "traefik.docker.network=traefik"
      # - "traefik.http.routers.waffles.rule=Host(`waffles.test`)"
      # - "traefik.http.routers.waffles.middlewares=http-redirect-https@file,headers@file"
      # - "traefik.http.routers.waffles-secure.entrypoints=https"
      # - "traefik.http.routers.waffles-secure.rule=Host(`waffles.test`)"
      # - "traefik.http.routers.waffles-secure.middlewares=headers@file"
      # - "traefik.http.routers.waffles-secure.tls=true"
    # networks:
      # - traefik
